apiVersion: v1
kind: Pod
metadata:
  name: slam-hive-web
  # namespace: slam-hive
spec:
  # nodeName: master-node # your master server hostname (need to change based on the kubernetes actual hostname)
  nodeName: xinzhe
  containers:
    - name: flask-mysql-kube
      image: mysql:8.0.31
      imagePullPolicy: IfNotPresent
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: SLAMHive1#
        # new database version
        - name: MYSQL_DATABASE
          value: slamhiveDB3
      securityContext:
        privileged: true
      ports:
        - name: mysql-port
          containerPort: 3306
          hostPort: 3307
      volumeMounts:
        - name: flask-mysql-1
          mountPath: /var/lib/mysql
        - name: flask-mysql-2
          mountPath: /docker-entrypoint-initdb.d
    - name: slam-hive-web-kube
      # image: slam-hive-web:aliyun_server
      image: slam-hive-web:2024_4_12
      imagePullPolicy: IfNotPresent
      ports:
        - name: web-port
          containerPort: 5000
          hostPort: 5000
        - name: test-web-port
          containerPort: 5001
          hostPort: 5001  
      securityContext:
        privileged: true
      volumeMounts:
        - name: slam-hive-web-1
          mountPath: /slam_hive_algos
        - name: slam-hive-web-2
          mountPath: /slam_hive_datasets
        - name: slam-hive-web-3
          mountPath: /slam_hive_results
        - name: slam-hive-web-4
          mountPath: /slam_hive_configurations
        - name: slam-hive-web-5
          mountPath: /var/run/docker.sock
        - name: slam-hive-web-6
          mountPath: /home/slam_hive_web
        - name: slam-hive-web-7
          mountPath: /root/.kube/config
        - name: slam-hive-web-8
          mountPath: /slam_hive_controller
    - name: cadvisor-kube
      image: google/cadvisor:latest
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: cadvisor-1
          mountPath: /rootfs
          readOnly: true
        - name: cadvisor-2
          mountPath: /var/run
          #readOnly: true
        - name: cadvisor-3
          mountPath: /sys
          readOnly: true
        - name: cadvisor-4
          mountPath: /var/lib/docker
          readOnly: true
        - name: cadvisor-5
          mountPath: /dev/disk
          readOnly: true
      securityContext:
        privileged: true
      # volumeDevices:
        # - name: cadvisor-device
          # devicePath: /dev/kmsg
      ports:
        - name: cadvisor-port
          containerPort: 8080
          hostPort: 8085


        
      
      
      
  restartPolicy: Always
  volumes:
    - name: flask-mysql-1
      hostPath:
        path: /SLAM-Hive/slam_hive_web/db/data
    - name: flask-mysql-2
      hostPath:
        path: /SLAM-Hive/slam_hive_web/db/sql

    - name: slam-hive-web-1
      hostPath:
        path: /SLAM-Hive/slam_hive_algos
    - name: slam-hive-web-2
      hostPath:
        path: /SLAM-Hive/slam_hive_datasets
    - name: slam-hive-web-3
      hostPath:
        path: /SLAM-Hive/slam_hive_results
    - name: slam-hive-web-4
      hostPath:
        path: /SLAM-Hive/slam_hive_configurations
    - name: slam-hive-web-5
      hostPath:
        path: /var/run/docker.sock
    - name: slam-hive-web-6
      hostPath:
        path: /SLAM-Hive/slam_hive_web
    - name: slam-hive-web-7
      hostPath:
        path: /root/.kube/config
    - name: slam-hive-web-8
      hostPath:
        path: /SLAM-Hive/slam_hive_controller
    - name: cadvisor-1
      hostPath:
        path: /
    - name: cadvisor-2
      hostPath:
        path: /var/run
    - name: cadvisor-3
      hostPath:
        path: /sys
    - name: cadvisor-4
      hostPath:
        path: /var/lib/docker
    - name: cadvisor-5
      hostPath:
        path: /dev/disk
    # - name: cadvisor-device
      # persistentVolumeClaim:
        # claimName: /dev/kmsg




