"""change length of parameter name

Revision ID: 57483d852c07
Revises: 837dc47878e8
Create Date: 2022-08-18 06:41:19.530270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57483d852c07'
down_revision = '837dc47878e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algoparameter', sa.Column('name2', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algoparameter', 'name2')
    # ### end Alembic commands ###
