"""change length of parameter name

Revision ID: 5b53992de70f
Revises: 9d0e2453205a
Create Date: 2022-08-18 06:52:05.489349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b53992de70f'
down_revision = '9d0e2453205a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('algoparameter', 'name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('algorithm', 'name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('mappingtaskconfig', 'name',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.String(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mappingtaskconfig', 'name',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('algorithm', 'name',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('algoparameter', 'name',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###
