"""change length of parameter name

Revision ID: 837dc47878e8
Revises: ea7536839449
Create Date: 2022-08-18 06:39:23.790375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '837dc47878e8'
down_revision = 'ea7536839449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algoparameter', 'name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algoparameter', sa.Column('name2', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
