"""change length of parameter name

Revision ID: 9d0e2453205a
Revises: 57483d852c07
Create Date: 2022-08-18 06:41:53.540719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d0e2453205a'
down_revision = '57483d852c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algoparameter', 'name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algoparameter', sa.Column('name2', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
