"""change length of parameter name

Revision ID: a4d36a08e0f3
Revises: 
Create Date: 2022-08-18 06:28:23.924496

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4d36a08e0f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mappingtask', 'name')
    op.drop_column('mappingtask', 'resultPath')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappingtask', sa.Column('resultPath', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('mappingtask', sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
    # ### end Alembic commands ###
