"""change length of parameter name

Revision ID: ea7536839449
Revises: a4d36a08e0f3
Create Date: 2022-08-18 06:39:05.045135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea7536839449'
down_revision = 'a4d36a08e0f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algoparameter', sa.Column('name2', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algoparameter', 'name2')
    # ### end Alembic commands ###
